#! /bin/sh
# Version 2022.41

re='[Vv]\(ersion\)\{0,1\} \{0,1\}2[0-9]\{3\}[.][0-9]'
for f in `git ls-files -m`
do
	if grep -q "$re" "$f"
	then
		:
	else
		continue
	fi
	if git diff "$f" | grep -q "^+ .*$re"
	then
		:
	else
		echo "Bump the revision of $f before checking in!" >& 2
		false || exit
	fi
done
