#! /bin/sh
# Version 2019.79

re='[Vv]ersion 2[0-9]\{3\}[.][0-9]'
for f in `git ls-files -m`
do
	if grep -q "$re"
	then
		:
	else
		continue
	fi
	if git diff "$f" | grep -q "^- $re"
	then
		:
	else
		echo "Bump the revision of $f before checking in!" >& 2
		false || exit
	fi
done
